# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('image', models.ImageField(upload_to=tagger.models.upload_to_images, verbose_name='image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('images', models.ManyToManyField(to='tagger.ImageT', verbose_name='image')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
    ]
