# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='images',
            field=models.ManyToManyField(related_name='tags', to='tagger.ImageT', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='name'),
        ),
    ]
